// src/components/AiPanelInline.vue
<script setup lang="ts">
/**
 * AiPanelInline.vue — 🤖 AI 辅助浮层面板（浮层内嵌版）。
 *
 * 与 AiPanel.vue 共享同一 useAiPanel 状态，但渲染为浮层内嵌布局：
 * - 无遮罩/居中卡片，直接填充 FloatingPanel 容器
 * - 动作按钮紧凑排列（摘要/翻译/解释/改写）
 * - 选区预览 + 结果展示在面板内滚动
 * - 复制/应用/重试操作按钮
 */
import { computed, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import type { AiAction } from "../composables/useAiPanel";
import { SELECTION_ACTIONS } from "../composables/useAiPanel";
import type { AiError } from "../composables/aiProvider";
import { renderMarkdown } from "../composables/useMarkdown";
import { copyTextToClipboard } from "../composables/clipboard";

const props = defineProps<{
  selectionText: string;
  result: string;
  loading: boolean;
  error: AiError | null;
  activeAction: AiAction | null;
  /** 是否有选区（来自批注工具栏的「AI」按钮） */
  hasExternalSelection?: boolean;
}>();

const emit = defineEmits<{
  (e: "run-action", action: AiAction): void;
  (e: "apply-result"): void;
  (e: "close"): void;
}>();

const { t } = useI18n();

const ACTIONS: { id: AiAction; key: string }[] = [
  { id: "summarize", key: "ai.summarize" },
  { id: "translate", key: "ai.translate" },
  { id: "explain", key: "ai.explain" },
  { id: "rewrite", key: "ai.rewrite" },
];

const hasSelection = computed(() => props.selectionText.trim().length > 0);
const isRewrite = computed(() => props.activeAction === "rewrite");
const canApply = computed(
  () => isRewrite.value && props.result.trim().length > 0 && !props.loading
);

const errorMessage = computed(() => {
  if (!props.error) return "";
  const title = t(`ai.error.${props.error.code}`);
  return props.error.detail ? `${title}：${props.error.detail}` : title;
});

const renderedHtml = ref("");
watch(
  () => props.result,
  async (result) => {
    if (!result) {
      renderedHtml.value = "";
      return;
    }
    try {
      renderedHtml.value = await renderMarkdown(result);
    } catch {
      renderedHtml.value = "";
    }
  },
  { immediate: true }
);

const copied = ref(false);
let copiedTimer: ReturnType<typeof setTimeout> | null = null;
async function onCopyResult(): Promise<void> {
  if (!props.result) return;
  try {
    await copyTextToClipboard(props.result);
    copied.value = true;
    if (copiedTimer) clearTimeout(copiedTimer);
    copiedTimer = setTimeout(() => (copied.value = false), 2000);
  } catch {
    copied.value = false;
  }
}

function onAction(action: AiAction): void {
  if (props.loading) return;
  if (SELECTION_ACTIONS.has(action) && !hasSelection.value) return;
  emit("run-action", action);
}
</script>

<template>
  <div class="ai-inline">
    <div class="ai-inline-header">
      <span class="ai-inline-title">{{ t("ai.title") }}</span>
      <span v-if="loading" class="ai-inline-loading">{{ t("ai.loading") }}</span>
    </div>

    <div class="ai-inline-body">
      <!-- 选区预览 -->
      <div class="ai-inline-section">
        <div class="ai-inline-selection" data-test="selection">
          <template v-if="hasSelection">
            <span class="ai-inline-sel-label">{{ t("ai.selection") }}</span>
            <span class="ai-inline-sel-text">{{ selectionText }}</span>
          </template>
          <span v-else class="ai-inline-sel-empty">
            {{ t("ai.noSelection") }}
          </span>
        </div>
        <div class="ai-inline-actions">
          <button
            v-for="a in ACTIONS"
            :key="a.id"
            class="ai-inline-btn"
            :class="{ disabled: SELECTION_ACTIONS.has(a.id) && !hasSelection }"
            :data-action="a.id"
            :disabled="loading || (SELECTION_ACTIONS.has(a.id) && !hasSelection)"
            @click="onAction(a.id)"
          >
            {{ t(a.key) }}
          </button>
        </div>
      </div>

      <!-- 错误态 -->
      <div v-if="error" class="ai-inline-error" data-test="error">
        <span class="ai-inline-error-msg">{{ errorMessage }}</span>
        <button
          v-if="activeAction"
          class="ai-inline-retry"
          data-action="retry"
          @click="emit('run-action', activeAction)"
        >
          {{ t("ai.retry") }}
        </button>
      </div>

      <!-- 结果区 -->
      <div v-if="result" class="ai-inline-result" data-test="result">
        <div class="ai-inline-result-actions">
          <button class="ai-inline-copy" data-action="copy" @click="onCopyResult">
            {{ copied ? t("ai.copied") : t("ai.copy") }}
          </button>
          <button
            v-if="canApply"
            class="ai-inline-apply"
            data-action="apply"
            @click="emit('apply-result')"
          >
            {{ t("ai.apply") }}
          </button>
        </div>
        <div
          v-if="renderedHtml"
          class="ai-inline-result-html markdown-body"
          v-html="renderedHtml"
        ></div>
        <pre v-else class="ai-inline-result-plain">{{ result }}</pre>
      </div>
    </div>
  </div>
</template>

<style scoped>
.ai-inline {
  flex: 1 1 auto;
  display: flex;
  flex-direction: column;
  min-height: 0;
  font-size: 13px;
}

.ai-inline-header {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px 8px;
  border-bottom: 1px solid var(--float-panel-header-border);
}

.ai-inline-title {
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.6px;
  color: var(--float-panel-header-fg);
}

.ai-inline-loading {
  font-size: 11px;
  color: var(--link);
  animation: ai-pulse 1.2s ease-in-out infinite;
}

@keyframes ai-pulse {
  0%, 100% { opacity: 0.6; }
  50% { opacity: 1; }
}

.ai-inline-body {
  flex: 1 1 auto;
  overflow-y: auto;
  padding: 8px 16px 12px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.ai-inline-section {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.ai-inline-selection {
  display: flex;
  align-items: baseline;
  gap: 6px;
  padding: 6px 10px;
  border: 1px solid var(--border);
  border-radius: 5px;
  background: var(--bg-btn);
  font-size: 12px;
  max-height: 60px;
  overflow: auto;
}

.ai-inline-sel-label {
  flex: 0 0 auto;
  color: var(--fg-muted);
  font-size: 11px;
}

.ai-inline-sel-text {
  white-space: pre-wrap;
  word-break: break-word;
  font-size: 12px;
}

.ai-inline-sel-empty {
  color: var(--fg-muted);
  font-size: 12px;
}

.ai-inline-actions {
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
}

.ai-inline-btn {
  padding: 4px 10px;
  font-size: 12px;
  border-radius: 5px;
  border: 1px solid var(--border);
  background: var(--bg-btn);
  color: var(--fg);
  cursor: pointer;
  transition: background-color 0.12s;
}

.ai-inline-btn:hover:not(:disabled) {
  background: var(--bg-btn-hover);
}

.ai-inline-btn:disabled,
.ai-inline-btn.disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

.ai-inline-error {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  border: 1px solid color-mix(in srgb, var(--mdr-danger) 35%, transparent);
  border-radius: 5px;
  background: color-mix(in srgb, var(--mdr-danger) 8%, transparent);
  font-size: 12px;
}

.ai-inline-error-msg {
  flex: 1 1 auto;
  color: var(--critic-del-color, #dc2626);
  word-break: break-word;
}

.ai-inline-retry {
  flex: 0 0 auto;
  padding: 2px 8px;
  font-size: 11px;
  border-radius: 4px;
  border: 1px solid var(--border);
  background: var(--bg-btn);
  color: var(--fg);
  cursor: pointer;
}

.ai-inline-result {
  border-top: 1px solid var(--border);
  padding-top: 8px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.ai-inline-result-actions {
  display: flex;
  gap: 6px;
  justify-content: flex-end;
}

.ai-inline-result-actions button {
  padding: 2px 10px;
  font-size: 11px;
  border-radius: 4px;
  border: 1px solid var(--border);
  background: var(--bg-btn);
  color: var(--fg);
  cursor: pointer;
}

.ai-inline-result-actions .ai-inline-apply {
  border-color: var(--critic-ins-color, #16a34a);
  color: var(--critic-ins-color, #16a34a);
}

.ai-inline-result-html {
  font-size: 13px;
  line-height: 1.5;
}

.ai-inline-result-plain {
  margin: 0;
  padding: 6px 10px;
  border: 1px solid var(--border);
  border-radius: 5px;
  background: var(--bg-btn);
  white-space: pre-wrap;
  word-break: break-word;
  font-family: var(--editor-font-family, monospace);
  font-size: 12px;
}
</style>

// src/components/AiPanelInline.svelte
<script lang="ts">
/**
 * AiPanelInline.svelte — 🤖 AI 辅助浮层面板（浮层内嵌版）。
 *
 * 与 AiPanel.vue 共享同一 useAiPanel 状态，但渲染为浮层内嵌布局：
 * - 无遮罩/居中卡片，直接填充 FloatingPanel 容器
 * - 动作按钮紧凑排列（摘要/翻译/解释/改写）
 * - 选区预览 + 结果展示在面板内滚动
 * - 复制/应用/重试操作按钮
 */
import { t } from "../i18n/locale.svelte.ts";
import type { AiAction } from "../composables/useAiPanel.svelte.ts";
import { SELECTION_ACTIONS } from "../composables/useAiPanel.svelte.ts";
import type { AiError } from "../composables/aiProvider";
import { renderMarkdown } from "../composables/useMarkdown";
import { copyTextToClipboard } from "../composables/clipboard";

interface Props {
  selectionText: string;
  result: string;
  loading: boolean;
  error: AiError | null;
  activeAction: AiAction | null;
  /** 是否有选区（来自批注工具栏的「AI」按钮） */
  hasExternalSelection?: boolean;
  onRunAction?: (action: AiAction) => void;
  onApplyResult?: () => void;
  onClose?: () => void;
}

let { selectionText, result, loading, error, activeAction, onRunAction, onApplyResult }: Props =
  $props();

const ACTIONS: { id: AiAction; key: string }[] = [
  { id: "summarize", key: "ai.summarize" },
  { id: "translate", key: "ai.translate" },
  { id: "explain", key: "ai.explain" },
  { id: "rewrite", key: "ai.rewrite" },
];

const hasSelection = $derived(selectionText.trim().length > 0);
const isRewrite = $derived(activeAction === "rewrite");
const canApply = $derived(isRewrite && result.trim().length > 0 && !loading);

const errorMessage = $derived.by(() => {
  if (!error) return "";
  const title = t(`ai.error.${error.code}`);
  return error.detail ? `${title}：${error.detail}` : title;
});

let renderedHtml = $state("");

// result 变化即异步渲染 Markdown（原 watch immediate）
$effect(() => {
  const r = result;
  if (!r) {
    renderedHtml = "";
    return;
  }
  renderMarkdown(r)
    .then((html) => {
      renderedHtml = html;
    })
    .catch(() => {
      renderedHtml = "";
    });
});

let copied = $state(false);
let copiedTimer: ReturnType<typeof setTimeout> | null = null;

async function onCopyResult(): Promise<void> {
  if (!result) return;
  try {
    await copyTextToClipboard(result);
    copied = true;
    if (copiedTimer) clearTimeout(copiedTimer);
    copiedTimer = setTimeout(() => (copied = false), 2000);
  } catch {
    copied = false;
  }
}

function onAction(action: AiAction): void {
  if (loading) return;
  if (SELECTION_ACTIONS.has(action) && !hasSelection) return;
  onRunAction?.(action);
}

/* 动作按钮：可用态带 hover 换色，禁用态互斥（原 :disabled / .disabled 选择器） */
const BTN_BASE =
  "ai-inline-btn cursor-pointer rounded-[5px] border border-border bg-bg-btn px-2.5 py-1 " +
  "text-[12px] text-fg transition-[background-color] duration-[120ms] ease-[ease] hover:bg-bg-btn-hover";
const BTN_DISABLED =
  "ai-inline-btn cursor-not-allowed rounded-[5px] border border-border bg-bg-btn px-2.5 py-1 " +
  "text-[12px] text-fg opacity-45 transition-[background-color] duration-[120ms] ease-[ease]";

function btnCls(id: AiAction): string {
  const disabled = loading || (SELECTION_ACTIONS.has(id) && !hasSelection);
  return disabled ? BTN_DISABLED : BTN_BASE;
}

/* 结果区两个按钮：apply 覆盖边框/文字色（原 .ai-inline-apply 选择器） */
const COPY_CLS =
  "ai-inline-copy cursor-pointer rounded border border-border bg-bg-btn px-2.5 py-0.5 text-[11px] text-fg";
const APPLY_CLS =
  "ai-inline-apply cursor-pointer rounded border border-critic-ins-color bg-bg-btn px-2.5 py-0.5 text-[11px] text-critic-ins-color";
</script>

<div class="ai-inline flex min-h-0 flex-1 flex-col text-[13px]">
  <div class="ai-inline-header flex shrink-0 items-center gap-2 border-b border-float-panel-header-border px-4 pb-2 pt-3">
    <span class="ai-inline-title text-[12px] uppercase tracking-[0.6px] text-float-panel-header-fg">{t("ai.title")}</span>
    {#if loading}
      <span class="ai-inline-loading text-[11px] text-link animate-[aiPulse_1.2s_ease-in-out_infinite]">{t("ai.loading")}</span>
    {/if}
  </div>

  <div class="ai-inline-body flex min-h-0 flex-1 flex-col gap-2.5 overflow-y-auto px-4 pb-3 pt-2">
    <!-- 选区预览 -->
    <div class="ai-inline-section flex flex-col gap-2">
      <div class="ai-inline-selection flex max-h-[60px] items-baseline gap-1.5 overflow-auto rounded-[5px] border border-border bg-bg-btn px-2.5 py-1.5 text-[12px]" data-test="selection">
        {#if hasSelection}
          <span class="ai-inline-sel-label shrink-0 text-[11px] text-fg-muted">{t("ai.selection")}</span>
          <span class="ai-inline-sel-text whitespace-pre-wrap text-[12px] [word-break:break-word]">{selectionText}</span>
        {:else}
          <span class="ai-inline-sel-empty text-[12px] text-fg-muted">
            {t("ai.noSelection")}
          </span>
        {/if}
      </div>
      <div class="ai-inline-actions flex flex-wrap gap-1">
        {#each ACTIONS as a (a.id)}
          <button
            class={btnCls(a.id)}
            data-action={a.id}
            disabled={loading || (SELECTION_ACTIONS.has(a.id) && !hasSelection)}
            onclick={() => onAction(a.id)}
          >
            {t(a.key)}
          </button>
        {/each}
      </div>
    </div>

    <!-- 错误态 -->
    {#if error}
      <div
        class="ai-inline-error flex items-center gap-2 rounded-[5px] border border-[color:color-mix(in_srgb,var(--mdr-danger)_35%,transparent)] bg-[color:color-mix(in_srgb,var(--mdr-danger)_8%,transparent)] px-2.5 py-1.5 text-[12px]"
        data-test="error"
      >
        <span class="ai-inline-error-msg min-w-0 flex-1 text-critic-del-color [word-break:break-word]">{errorMessage}</span>
        {#if activeAction}
          <button
            class="ai-inline-retry shrink-0 cursor-pointer rounded border border-border bg-bg-btn px-2 py-0.5 text-[11px] text-fg"
            data-action="retry"
            onclick={() => onRunAction?.(activeAction)}
          >
            {t("ai.retry")}
          </button>
        {/if}
      </div>
    {/if}

    <!-- 结果区 -->
    {#if result}
      <div class="ai-inline-result flex flex-col gap-1.5 border-t border-border pt-2" data-test="result">
        <div class="ai-inline-result-actions flex justify-end gap-1.5">
          <button class={COPY_CLS} data-action="copy" onclick={onCopyResult}>
            {copied ? t("ai.copied") : t("ai.copy")}
          </button>
          {#if canApply}
            <button class={APPLY_CLS} data-action="apply" onclick={() => onApplyResult?.()}>
              {t("ai.apply")}
            </button>
          {/if}
        </div>
        {#if renderedHtml}
          <div class="ai-inline-result-html markdown-body text-[13px] leading-[1.5]">{@html renderedHtml}</div>
        {:else}
          <pre class="ai-inline-result-plain m-0 whitespace-pre-wrap rounded-[5px] border border-border bg-bg-btn px-2.5 py-1.5 text-[12px] [font-family:var(--editor-font-family,monospace)] [word-break:break-word]">{result}</pre>
        {/if}
      </div>
    {/if}
  </div>
</div>
