// src/components/FloatPanelContent.vue
<template>
  <FloatingPanel
    :visible="!!floatState.activeLeftPanel"
    :side="isMobile ? 'bottom' : 'left'"
    :width="320"
    @close="floatState.closePanel"
  >
    <template v-if="floatState.activeLeftPanel === 'filetree'">
      <div class="float-panel-header">{{ t("float.filetree") }}</div>
      <div class="float-panel-body tree-scroll" ref="treeScrollEl">
        <FileTree
          v-if="rootDir"
          :nodes="tree" :current-path="currentFile" :scroll-container="treeScrollEl"
          :can-go-up="canGoUp" :focus-key="treeFocusKey"
          :root-dir="rootDir" :load-children="loadChildren"
          @open="emit('openFile', $event)" @go-up="emit('goUp')"
        />
        <div v-else class="empty-tip">{{ t("app.openFolderHint") }}</div>
      </div>
    </template>
    <template v-else-if="floatState.activeLeftPanel === 'history'">
      <HistoryPanel :items="recentFiltered" :current-path="currentFile" @open="p => emit('open', p)" @clear="emit('refreshRecent')" />
    </template>
    <template v-else-if="floatState.activeLeftPanel === 'annotations'">
      <AnnotationList :source="draftContent" :file-name="currentFile"
                      @focus="emit('annotationFocus', $event)" @open-review="emit('openReview')"
                      @copy-ai="() => emit('copyAi')" />
    </template>
    <template v-else-if="floatState.activeLeftPanel === 'bookmark'">
      <BookmarkPanel :current-path="currentFile" :show-current-only="true"
                     @jump="(p, s) => emit('bookmarkJump', p, s)" @refresh="emit('refreshBookmarks')" />
    </template>
    <template v-else-if="floatState.activeLeftPanel === 'ai'">
      <AiPanelInline
        :selection-text="aiPanel.state.selectionText" :result="aiPanel.state.result"
        :loading="aiPanel.state.loading" :error="aiPanel.state.error"
        :active-action="aiPanel.state.activeAction"
        @run-action="(a) => emit('runAiAction', a)"
        @apply-result="() => emit('applyAiResult')"
        @close="floatState.closePanel"
      />
    </template>
    <template v-else-if="floatState.activeLeftPanel === 'settings'">
      <QuickSettings
        :theme="theme"
        :font-size="isEditing ? readingSettings.editorFontSize : readingSettings.fontSize"
        :float-layout-enabled="floatLayoutEnabled"
        @toggle-theme="emit('toggleTheme')"
        @open-settings="emit('openSettings')"
        @zoom-in="emit('zoomIn')" @zoom-out="emit('zoomOut')"
        @set-max-width="emit('setMaxWidth', $event)" @set-line-height="emit('setLineHeight', $event)"
        @toggle-float-layout="emit('toggleFloatLayout')"
      />
    </template>
    <template v-else-if="floatState.activeLeftPanel === 'help'">
      <HelpPanel />
    </template>
  </FloatingPanel>
</template>

<script setup lang="ts">
import FloatingPanel from "./FloatingPanel.vue";
import FileTree from "./FileTree.vue";
import HistoryPanel from "./HistoryPanel.vue";
import AnnotationList from "./AnnotationList.vue";
import BookmarkPanel from "./BookmarkPanel.vue";
import AiPanelInline from "./AiPanelInline.vue";
import QuickSettings from "./QuickSettings.vue";
import HelpPanel from "./HelpPanel.vue";
import { useI18n } from "vue-i18n";
import { ref } from "vue";
import type { LeftPanelID } from "../composables/useFloatLayout";
import type { TreeNode } from "../composables/useFileTree";
import type { RecentItem } from "../stores/useHistoryStore";
import type { AiPanelState, AiAction } from "../composables/useAiPanel";

const { t } = useI18n();
const treeScrollEl = ref<HTMLElement | null>(null);

defineProps<{
  floatState: { activeLeftPanel: LeftPanelID | null; closePanel: () => void };
  isMobile: boolean;
  rootDir: string | null;
  tree: TreeNode[];
  currentFile: string;
  canGoUp: boolean;
  treeFocusKey: number;
  loadChildren: (dir: TreeNode) => Promise<void>;
  recentFiltered: RecentItem[];
  draftContent: string;
  theme: "light" | "dark";
  isEditing: boolean;
  readingSettings: { editorFontSize: number; fontSize: number };
  floatLayoutEnabled: boolean;
  showSettings: boolean;
  aiPanel: { state: AiPanelState };
}>();

const emit = defineEmits<{
  (e: "openFile", path: string): void;
  (e: "goUp"): void;
  (e: "open", path: string): void;
  (e: "refreshRecent"): void;
  (e: "annotationFocus", id: number): void;
  (e: "openReview"): void;
  (e: "copyAi"): void;
  (e: "bookmarkJump", path: string, scrollTop: number): void;
  (e: "runAiAction", action: AiAction): void;
  (e: "applyAiResult"): void;
  (e: "toggleTheme"): void;
  (e: "zoomIn"): void;
  (e: "zoomOut"): void;
  (e: "setMaxWidth", v: number): void;
  (e: "setLineHeight", v: number): void;
  (e: "toggleFloatLayout"): void;
  (e: "openSettings"): void;
  (e: "refreshBookmarks"): void;
}>();
</script>

// src/components/FloatPanelContent.svelte
<script lang="ts">
/**
 * FloatPanelContent.svelte — 悬浮左侧面板内容分发器（按 activeLeftPanel 切换 7 种面板）。
 *
 * - Vue `defineProps`（16 个）/ `defineEmits`（18 个）→ `$props()` + `onXxx` 回调 props
 * - 8 个子组件 import 全部指向已迁移的 `.svelte`（Ruling 1）
 * - `ref<HTMLElement>("treeScrollEl")` → `$state` + `bind:this`
 * - 无 `<style>` 块：`float-panel-header/body`、`tree-scroll`、`empty-tip` 均为
 *   legacy-components.css 的全局类，按 Ruling 11 保留原样（App 侧未引用，纯本组件渲染）
 */
import FloatingPanel from "./FloatingPanel.svelte";
import FileTree from "./FileTree.svelte";
import HistoryPanel from "./HistoryPanel.svelte";
import AnnotationList from "./AnnotationList.svelte";
import BookmarkPanel from "./BookmarkPanel.svelte";
import AiPanelInline from "./AiPanelInline.svelte";
import QuickSettings from "./QuickSettings.svelte";
import HelpPanel from "./HelpPanel.svelte";
import { t } from "../i18n/locale.svelte.ts";
import type { LeftPanelID } from "../composables/useFloatLayout.svelte.ts";
import type { TreeNode } from "../composables/useFileTree.svelte.ts";
import type { RecentItem } from "../composables/useHistory";
import type { AiPanelState, AiAction } from "../composables/useAiPanel.svelte.ts";

interface Props {
  floatState: { activeLeftPanel: LeftPanelID | null; closePanel: () => void };
  isMobile: boolean;
  rootDir: string | null;
  tree: TreeNode[];
  currentFile: string;
  canGoUp: boolean;
  treeFocusKey: number;
  loadChildren: (dir: TreeNode) => Promise<void>;
  recentFiltered: RecentItem[];
  draftContent: string;
  theme: "light" | "dark";
  isEditing: boolean;
  readingSettings: { editorFontSize: number; fontSize: number };
  floatLayoutEnabled: boolean;
  /** App.vue 仍传入，但 Vue 版模板自始未引用 —— 只声明不解构（noUnusedLocals） */
  showSettings: boolean;
  aiPanel: { state: AiPanelState };
  onOpenFile?: (path: string) => void;
  onGoUp?: () => void;
  onOpen?: (path: string) => void;
  onRefreshRecent?: () => void;
  onAnnotationFocus?: (id: number) => void;
  onOpenReview?: () => void;
  onCopyAi?: () => void;
  onBookmarkJump?: (path: string, scrollTop: number) => void;
  onRunAiAction?: (action: AiAction) => void;
  onApplyAiResult?: () => void;
  onToggleTheme?: () => void;
  onZoomIn?: () => void;
  onZoomOut?: () => void;
  onSetMaxWidth?: (v: number) => void;
  onSetLineHeight?: (v: number) => void;
  onToggleFloatLayout?: () => void;
  onOpenSettings?: () => void;
  onRefreshBookmarks?: () => void;
}

let {
  floatState,
  isMobile,
  rootDir,
  tree,
  currentFile,
  canGoUp,
  treeFocusKey,
  loadChildren,
  recentFiltered,
  draftContent,
  theme,
  isEditing,
  readingSettings,
  floatLayoutEnabled,
  aiPanel,
  onOpenFile,
  onGoUp,
  onOpen,
  onRefreshRecent,
  onAnnotationFocus,
  onOpenReview,
  onCopyAi,
  onBookmarkJump,
  onRunAiAction,
  onApplyAiResult,
  onToggleTheme,
  onZoomIn,
  onZoomOut,
  onSetMaxWidth,
  onSetLineHeight,
  onToggleFloatLayout,
  onOpenSettings,
  onRefreshBookmarks,
}: Props = $props();

/** 文件树滚动容器（原 Vue `ref="treeScrollEl"`，交 FileTree 做滚动定位） */
let treeScrollEl = $state<HTMLElement | null>(null);
</script>

<FloatingPanel
  visible={!!floatState.activeLeftPanel}
  side={isMobile ? "bottom" : "left"}
  width={320}
  onClose={floatState.closePanel}
>
  {#if floatState.activeLeftPanel === "filetree"}
    <div class="float-panel-header">{t("float.filetree")}</div>
    <div class="float-panel-body tree-scroll" bind:this={treeScrollEl}>
      {#if rootDir}
        <FileTree
          nodes={tree}
          currentPath={currentFile}
          scrollContainer={treeScrollEl}
          canGoUp={canGoUp}
          focusKey={treeFocusKey}
          rootDir={rootDir}
          loadChildren={loadChildren}
          onOpen={onOpenFile}
          onGoUp={onGoUp}
        />
      {:else}
        <div class="empty-tip">{t("app.openFolderHint")}</div>
      {/if}
    </div>
  {:else if floatState.activeLeftPanel === "history"}
    <HistoryPanel items={recentFiltered} currentPath={currentFile} onOpen={onOpen} onClear={onRefreshRecent} />
  {:else if floatState.activeLeftPanel === "annotations"}
    <AnnotationList
      source={draftContent}
      fileName={currentFile}
      onFocus={onAnnotationFocus}
      onOpenReview={onOpenReview}
      onCopyAi={onCopyAi}
    />
  {:else if floatState.activeLeftPanel === "bookmark"}
    <BookmarkPanel currentPath={currentFile} showCurrentOnly={true} onJump={onBookmarkJump} onRefresh={onRefreshBookmarks} />
  {:else if floatState.activeLeftPanel === "ai"}
    <AiPanelInline
      selectionText={aiPanel.state.selectionText}
      result={aiPanel.state.result}
      loading={aiPanel.state.loading}
      error={aiPanel.state.error}
      activeAction={aiPanel.state.activeAction}
      onRunAction={onRunAiAction}
      onApplyResult={onApplyAiResult}
      onClose={floatState.closePanel}
    />
  {:else if floatState.activeLeftPanel === "settings"}
    <QuickSettings
      theme={theme}
      fontSize={isEditing ? readingSettings.editorFontSize : readingSettings.fontSize}
      floatLayoutEnabled={floatLayoutEnabled}
      onToggleTheme={onToggleTheme}
      onOpenSettings={onOpenSettings}
      onZoomIn={onZoomIn}
      onZoomOut={onZoomOut}
      onSetMaxWidth={onSetMaxWidth}
      onSetLineHeight={onSetLineHeight}
      onToggleFloatLayout={onToggleFloatLayout}
    />
  {:else if floatState.activeLeftPanel === "help"}
    <HelpPanel />
  {/if}
</FloatingPanel>
