// src/components/GrantAccessDialog.vue
<script setup lang="ts">
import { useI18n } from "vue-i18n";

const { t } = useI18n();

defineProps<{
  visible: boolean;
  dir: string;
  allowLabel?: string;
  denyLabel?: string;
}>();

const emit = defineEmits<{
  (e: "allow"): void;
  (e: "deny"): void;
}>();
</script>

<template>
  <div v-if="visible" class="overlay" @click.self="emit('deny')">
    <div class="dialog" role="dialog" aria-modal="true">
      <div class="title">{{ t("grant.title") }}</div>
      <div class="dir" :title="dir">{{ dir }}</div>
      <div class="message">{{ t("grant.message") }}</div>
      <div class="actions">
        <button class="btn" @click="emit('deny')">{{ denyLabel || t("grant.deny") }}</button>
        <button class="btn primary" @click="emit('allow')">{{ allowLabel || t("grant.allow") }}</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.42);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 60;
}
.dialog {
  width: min(520px, calc(100vw - 40px));
  background: var(--bg);
  color: var(--fg);
  border: 1px solid var(--border);
  border-radius: 10px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.35);
  padding: 22px 24px 18px;
}
.title {
  font-size: 16px;
  font-weight: 600;
  margin-bottom: 8px;
}
.dir {
  font-size: 13px;
  color: var(--link);
  margin-bottom: 12px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.message {
  font-size: 13px;
  line-height: 1.7;
  color: var(--fg-muted);
  margin-bottom: 20px;
}
.actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.btn {
  font-size: 13px;
  padding: 6px 14px;
  border-radius: 6px;
  border: 1px solid var(--border);
  background: var(--bg-btn);
  color: var(--fg);
  cursor: pointer;
}
.btn:hover {
  background: var(--bg-btn-hover);
}
.btn.primary {
  background: var(--link);
  color: #fff;
  border-color: var(--link);
}
</style>

// src/components/GrantAccessDialog.svelte
<script lang="ts">
  // 自研 i18n（原 vue-i18n useI18n → locale 模块 t()）
  import { t } from "../i18n/locale.svelte.ts";

  // 属性与回调：原 defineProps/defineEmits → Svelte 5 runes props
  interface Props {
    visible: boolean;
    dir: string;
    allowLabel?: string;
    denyLabel?: string;
    onAllow?: () => void;
    onDeny?: () => void;
  }

  let {
    visible,
    dir,
    allowLabel = undefined,
    denyLabel = undefined,
    onAllow,
    onDeny,
  }: Props = $props();

  //原 @click.self:仅点击遮罩自身（非对话框内部）才拒绝
  function handleOverlayClick(event: MouseEvent) {
    if (event.target === event.currentTarget) onDeny?.();
  }
</script>

{#if visible}
  <div
    class="overlay fixed inset-0 z-[60] flex items-center justify-center bg-[rgba(0,0,0,0.42)]"
    role="presentation"
    onclick={handleOverlayClick}
  >
    <div
      class="dialog w-[min(520px,calc(100vw-40px))] rounded-[10px] border border-border bg-bg px-6 pb-[18px] pt-[22px] text-fg shadow-[0_20px_60px_rgba(0,0,0,0.35)]"
      role="dialog"
      aria-modal="true"
    >
      <div class="title mb-2 text-base font-semibold">{t("grant.title")}</div>
      <div class="dir mb-3 truncate text-[13px] text-link" title={dir}>{dir}</div>
      <div class="message mb-5 text-[13px] leading-[1.7] text-fg-muted">{t("grant.message")}</div>
      <div class="actions flex justify-end gap-2">
        <button
          class="btn cursor-pointer rounded-md border border-border bg-bg-btn px-[14px] py-1.5 text-[13px] text-fg hover:bg-bg-btn-hover"
          onclick={() => onDeny?.()}>{denyLabel || t("grant.deny")}</button
        >
        <button
          class="btn primary cursor-pointer rounded-md border border-link bg-link px-[14px] py-1.5 text-[13px] text-white hover:bg-link"
          onclick={() => onAllow?.()}>{allowLabel || t("grant.allow")}</button
        >
      </div>
    </div>
  </div>
{/if}
