// src/components/LeftRail.svelte
<script lang="ts">
/**
 * 左侧竖排图标栏
 *
 * Vue → Svelte 5 迁移要点:
 * - ref → $state；onMounted/onUnmounted → onMount/onDestroy
 * - emit('open-panel') → callback prop onOpenPanel
 * - scoped CSS → Tailwind 工具类（token 见 @theme）
 */
import { onMount, onDestroy } from "svelte";
import { t } from "../i18n/locale.svelte.ts";
import { LEFT_PANEL_META, type LeftPanelID } from "../composables/useFloatLayout.svelte.ts";
import PanelIcon from "./PanelIcon.svelte";

let {
    activePanel,
    dynamicIcons = undefined,
    onOpenPanel,
  }: {
    activePanel: LeftPanelID | null;
    dynamicIcons?: Record<string, string>;
    onOpenPanel?: (id: LeftPanelID) => void;
  } = $props();

let dimmed = $state(false);
let dimTimer: ReturnType<typeof setTimeout> | null = null;
let scrollTarget: HTMLElement | null = null;

const SCROLL_DIM_DELAY = 1500;

function onScroll(): void {
  dimmed = true;
  if (dimTimer !== null) clearTimeout(dimTimer);
  dimTimer = setTimeout(() => {
    dimmed = false;
  }, SCROLL_DIM_DELAY);
}

onMount(() => {
  scrollTarget = document.querySelector("[data-scroll-root]");
  scrollTarget?.addEventListener("scroll", onScroll, { passive: true });
});

onDestroy(() => {
  scrollTarget?.removeEventListener("scroll", onScroll);
  if (dimTimer !== null) clearTimeout(dimTimer);
});

const groupBoundaries = new Set(
  LEFT_PANEL_META.reduce<number[]>((acc, meta, idx) => {
    if (idx < LEFT_PANEL_META.length - 1 && LEFT_PANEL_META[idx + 1].group !== meta.group) {
      acc.push(idx);
    }
    return acc;
  }, [])
);
</script>

<nav
  class="left-rail fixed left-0 top-0 bottom-0 z-[45] flex w-10 flex-col items-center border-r-[0.5px] border-black/[0.04] bg-[var(--float-left-rail-bg)] backdrop-blur-[8px] select-none transition-[opacity,background-color] duration-200 ease-out hover:opacity-100 {dimmed
    ? 'dimmed opacity-25'
    : 'opacity-100'} dark:border-white/[0.04]"
  aria-label="toolbar"
>
  <div class="left-rail-inner flex w-full flex-1 flex-col items-center justify-center gap-[2px] py-2">
    {#each LEFT_PANEL_META as item, idx (item.id)}
      <button
        class="left-rail-btn flex h-8 w-8 cursor-pointer items-center justify-center rounded-md border-none bg-transparent p-0 transition-[background-color,color] duration-[120ms] ease-out {activePanel ===
        item.id
          ? 'active bg-[var(--float-rail-icon-active-bg)] text-[var(--float-rail-icon-active)]'
          : 'text-[var(--float-rail-icon-color)] hover:bg-[var(--float-rail-icon-hover-bg)] hover:text-fg'}"
        title={t(item.labelKey)}
        aria-label={t(item.labelKey)}
        aria-pressed={activePanel === item.id}
        onclick={() => onOpenPanel?.(item.id)}
      >
        {#if dynamicIcons?.[item.id]}
          <span class="pointer-events-none text-lg leading-none">{dynamicIcons[item.id]}</span>
        {:else}
          <PanelIcon name={item.id} />
        {/if}
      </button>
      {#if groupBoundaries.has(idx)}
        <div
          class="left-rail-sep mx-0 my-1 h-px w-5 shrink-0 bg-[var(--float-rail-separator)] opacity-50"
          aria-hidden="true"
        ></div>
      {/if}
    {/each}
  </div>
</nav>

// src/components/LeftRail.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { useI18n } from "vue-i18n";
import { LEFT_PANEL_META, type LeftPanelID } from "../composables/useFloatLayout";
import PanelIcon from "./PanelIcon.vue";

const props = defineProps<{
  activePanel: LeftPanelID | null;
  dynamicIcons?: Record<string, string>;
}>();

const emit = defineEmits<{ (e: "open-panel", id: LeftPanelID): void }>();

const { t } = useI18n();

const dimmed = ref(false);
let dimTimer: ReturnType<typeof setTimeout> | null = null;

const SCROLL_DIM_DELAY = 1500;
const SCROLL_ROOT_SELECTOR = "[data-scroll-root]";

function onScroll(): void {
  dimmed.value = true;
  if (dimTimer !== null) clearTimeout(dimTimer);
  dimTimer = setTimeout(() => { dimmed.value = false; }, SCROLL_DIM_DELAY);
}

let scrollTarget: HTMLElement | null = null;

onMounted(() => {
  scrollTarget = document.querySelector(SCROLL_ROOT_SELECTOR);
  scrollTarget?.addEventListener("scroll", onScroll, { passive: true });
});

onUnmounted(() => {
  scrollTarget?.removeEventListener("scroll", onScroll);
  if (dimTimer !== null) clearTimeout(dimTimer);
});

const groupBoundaries = new Set(
  LEFT_PANEL_META.reduce<number[]>((acc, meta, idx) => {
    if (idx < LEFT_PANEL_META.length - 1 && LEFT_PANEL_META[idx + 1].group !== meta.group) {
      acc.push(idx);
    }
    return acc;
  }, [])
);
</script>

<template>
  <nav class="left-rail" :class="{ dimmed }" aria-label="toolbar">
    <div class="left-rail-inner">
      <template v-for="(item, idx) in LEFT_PANEL_META" :key="item.id">
        <button
          class="left-rail-btn"
          :class="{ active: activePanel === item.id }"
          :title="t(item.labelKey)"
          :aria-label="t(item.labelKey)"
          :aria-pressed="activePanel === item.id"
          @click="emit('open-panel', item.id)"
        >
          <span v-if="props.dynamicIcons?.[item.id]" class="left-rail-icon-text">{{ props.dynamicIcons[item.id] }}</span>
          <PanelIcon v-else :name="item.id" />
        </button>
        <div v-if="groupBoundaries.has(idx)" class="left-rail-sep" aria-hidden="true"></div>
      </template>
    </div>
  </nav>
</template>

<style scoped>
.left-rail {
  position: fixed;
  left: 0;
  top: 0;
  bottom: 0;
  width: 40px;
  z-index: 45;
  display: flex;
  flex-direction: column;
  align-items: center;
  pointer-events: auto;
  background: var(--float-left-rail-bg);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  border-right: 0.5px solid rgba(0, 0, 0, 0.04);
  user-select: none;
  transition: opacity 200ms ease, background 0.2s ease;
}
.left-rail.dimmed { opacity: 0.25; }
.left-rail:hover { opacity: 1; }

.left-rail-inner {
  flex: 1 1 auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2px;
  padding: 8px 0;
}

.left-rail-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  padding: 0;
  border: none;
  border-radius: 6px;
  background: transparent;
  color: var(--float-rail-icon-color);
  cursor: pointer;
  transition: background-color 0.12s ease, color 0.12s ease;
}
.left-rail-btn:hover {
  background: var(--float-rail-icon-hover-bg);
  color: var(--fg);
}
.left-rail-btn.active {
  color: var(--float-rail-icon-active);
  background: var(--float-rail-icon-active-bg);
}

.left-rail-icon {
  font-size: 18px;
  line-height: 1;
  pointer-events: none;
}

.left-rail-sep {
  width: 20px;
  height: 1px;
  margin: 4px 0;
  background: var(--float-rail-separator);
  opacity: 0.5;
  flex-shrink: 0;
}

:root[data-theme="dark"] .left-rail {
  border-right-color: rgba(255, 255, 255, 0.04);
}
</style>
