// src/components/QuickSettings.vue
<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { useReadingSettings } from "../composables/useReadingSettings";

const props = defineProps<{
  theme: "light" | "dark";
  fontSize: number;
  floatLayoutEnabled?: boolean;
}>();

const emit = defineEmits<{
  (e: "toggle-theme"): void;
  (e: "open-settings"): void;
  (e: "zoom-in"): void;
  (e: "zoom-out"): void;
  (e: "set-max-width", width: number): void;
  (e: "set-line-height", height: number): void;
  (e: "toggle-float-layout"): void;
}>();

const { t } = useI18n();
const { settings } = useReadingSettings();

const themeLabel = computed(() =>
  props.theme === "dark" ? t("float.lightMode") : t("float.darkMode")
);

const MAX_WIDTH_PRESETS = [
  { label: "float.widthNarrow", value: 600 },
  { label: "float.widthMedium", value: 750 },
  { label: "float.widthWide", value: 900 },
];

const LINE_HEIGHT_PRESETS = [
  { label: "float.lineHeightTight", value: 1.4 },
  { label: "float.lineHeightNormal", value: 1.75 },
  { label: "float.lineHeightRelaxed", value: 2.0 },
];
</script>

<template>
  <div class="qs">
    <div class="qs-header">{{ t("float.quickSettings") }}</div>

    <div class="qs-body">
      <div class="qs-row">
        <span class="qs-label">{{ t("float.theme") }}</span>
        <button class="qs-btn" @click="emit('toggle-theme')">{{ themeLabel }}</button>
      </div>

      <div class="qs-row">
        <span class="qs-label">{{ t("float.fontSize") }}</span>
        <div class="qs-control">
          <button class="qs-btn qs-icon-btn" :disabled="fontSize <= 10" @click="emit('zoom-out')">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="5" y1="12" x2="19" y2="12" /></svg>
          </button>
          <span class="qs-value">{{ fontSize }}</span>
          <button class="qs-btn qs-icon-btn" :disabled="fontSize >= 28" @click="emit('zoom-in')">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
          </button>
        </div>
      </div>

      <div class="qs-row">
        <span class="qs-label">{{ t("float.maxWidth") }}</span>
        <div class="qs-btn-group">
          <button
            v-for="preset in MAX_WIDTH_PRESETS"
            :key="preset.value"
            class="qs-btn"
            :class="{ active: settings.maxWidth === preset.value }"
            @click="emit('set-max-width', preset.value)"
          >{{ t(preset.label) }}</button>
        </div>
      </div>

      <div class="qs-row">
        <span class="qs-label">{{ t("float.lineHeight") }}</span>
        <div class="qs-btn-group">
          <button
            v-for="preset in LINE_HEIGHT_PRESETS"
            :key="preset.value"
            class="qs-btn"
            :class="{ active: Math.abs(settings.lineHeight - preset.value) < 0.01 }"
            @click="emit('set-line-height', preset.value)"
          >{{ t(preset.label) }}</button>
        </div>
      </div>

      <div class="qs-row">
        <span class="qs-label">{{ t("float.floatLayout") }}</span>
        <button class="qs-btn" :class="{ active: floatLayoutEnabled }" @click="emit('toggle-float-layout')">
          {{ floatLayoutEnabled ? t("float.floatLayoutOn") : t("float.floatLayoutOff") }}
        </button>
      </div>
    </div>

    <div class="qs-footer">
      <button class="qs-link-btn" @click="emit('open-settings')">
        {{ t("float.fullSettings") }}
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-left: 4px"><polyline points="9 18 15 12 9 6" /></svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
.qs { flex: 1; display: flex; flex-direction: column; min-height: 0; font-size: 13px; }
.qs-header {
  flex: 0 0 auto; padding: 12px 16px 8px; border-bottom: 1px solid var(--float-panel-header-border);
  font-size: 12px; text-transform: uppercase; letter-spacing: 0.6px; color: var(--float-panel-header-fg);
}
.qs-body { flex: 1; overflow-y: auto; padding: 8px 16px; display: flex; flex-direction: column; gap: 12px; }
.qs-row { display: flex; align-items: center; gap: 10px; }
.qs-label { flex: 0 0 60px; font-size: 12px; color: var(--fg-muted); white-space: nowrap; }
.qs-control { display: flex; align-items: center; gap: 6px; }
.qs-value { min-width: 24px; text-align: center; font-size: 12px; color: var(--fg); font-variant-numeric: tabular-nums; }
.qs-btn-group { display: flex; gap: 4px; flex-wrap: wrap; }
.qs-btn {
  padding: 3px 10px; font-size: 12px; border: 1px solid var(--border); border-radius: 5px;
  background: var(--bg-btn); color: var(--fg); cursor: pointer; white-space: nowrap;
}
.qs-btn:hover { background: var(--bg-btn-hover); }
.qs-btn.active { background: var(--bg-active); border-color: var(--link); color: var(--link); }
.qs-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.qs-icon-btn { display: flex; align-items: center; justify-content: center; width: 28px; height: 28px; padding: 0; }
.qs-footer {
  flex: 0 0 auto; padding: 8px 16px 12px; border-top: 1px solid var(--float-panel-header-border);
  display: flex; justify-content: flex-end;
}
.qs-link-btn {
  display: flex; align-items: center; padding: 4px 12px; font-size: 12px;
  border: 1px solid var(--border); border-radius: 5px; background: transparent; color: var(--link); cursor: pointer;
}
.qs-link-btn:hover { background: var(--bg-active); }
</style>

// src/components/QuickSettings.svelte
<script lang="ts">
  /**
   * QuickSettings.vue → .svelte 迁移要点:
   * - defineEmits("toggle-theme") 等 → 回调 prop onToggleTheme / onSetMaxWidth / …
   * - computed(themeLabel) → $derived
   * - const { settings } = useReadingSettings() 会固化初始 settings 对象，
   *   改为持有 rs，在模板内读 rs.settings.* 以跟随 store 的整体重赋值
   * - scoped CSS → Tailwind；同名工具类同 layer 内顺序不可控，故按态拆完整类串
   */
  import { t } from "../i18n/locale.svelte.ts";
  import { useReadingSettings } from "../composables/useReadingSettings.svelte.ts";

  interface Props {
    theme: "light" | "dark";
    fontSize: number;
    floatLayoutEnabled?: boolean;
    onToggleTheme?: () => void;
    onOpenSettings?: () => void;
    onZoomIn?: () => void;
    onZoomOut?: () => void;
    onSetMaxWidth?: (width: number) => void;
    onSetLineHeight?: (height: number) => void;
    onToggleFloatLayout?: () => void;
  }

  let {
    theme,
    fontSize,
    floatLayoutEnabled,
    onToggleTheme,
    onOpenSettings,
    onZoomIn,
    onZoomOut,
    onSetMaxWidth,
    onSetLineHeight,
    onToggleFloatLayout,
  }: Props = $props();

  const rs = useReadingSettings();

  const themeLabel = $derived(
    theme === "dark" ? t("float.lightMode") : t("float.darkMode")
  );

  const MAX_WIDTH_PRESETS = [
    { label: "float.widthNarrow", value: 600 },
    { label: "float.widthMedium", value: 750 },
    { label: "float.widthWide", value: 900 },
  ];

  const LINE_HEIGHT_PRESETS = [
    { label: "float.lineHeightTight", value: 1.4 },
    { label: "float.lineHeightNormal", value: 1.75 },
    { label: "float.lineHeightRelaxed", value: 2.0 },
  ];

  /* .qs-btn.active 源顺序在 .qs-btn:hover 之后 → 激活态悬停不变色，故 active 不带 hover:bg-*；
     .qs-icon-btn 覆盖 padding 为 0，故图标按钮不复用 btnBase 的 px/py */
  const btnBase =
    "qs-btn cursor-pointer whitespace-nowrap rounded-[5px] border px-2.5 py-[3px] text-[12px] disabled:cursor-not-allowed disabled:opacity-40";
  const btnNormal = btnBase + " border-border bg-bg-btn text-fg hover:bg-bg-btn-hover";
  const btnActive = btnBase + " border-link bg-active text-link";
  const iconBtnBase =
    "qs-btn qs-icon-btn flex h-7 w-7 cursor-pointer items-center justify-center whitespace-nowrap rounded-[5px] border p-0 text-[12px] disabled:cursor-not-allowed disabled:opacity-40";
  const iconBtnNormal =
    iconBtnBase + " border-border bg-bg-btn text-fg hover:bg-bg-btn-hover";
  const linkBtn =
    "qs-link-btn flex cursor-pointer items-center rounded-[5px] border border-border bg-transparent px-3 py-1 text-[12px] text-link hover:bg-active";
</script>

<div class="qs flex min-h-0 flex-1 flex-col text-[13px]">
  <div
    class="qs-header flex-none border-b border-float-panel-header-border px-4 pb-2 pt-3 text-[12px] tracking-[0.6px] uppercase text-float-panel-header-fg">{t("float.quickSettings")}</div
  >

  <div class="qs-body flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto px-4 py-2">
    <div class="qs-row flex items-center gap-2.5">
      <span class="qs-label shrink-0 basis-[60px] whitespace-nowrap text-[12px] text-fg-muted">{t("float.theme")}</span>
      <button class={btnNormal} onclick={onToggleTheme}>{themeLabel}</button>
    </div>

    <div class="qs-row flex items-center gap-2.5">
      <span class="qs-label shrink-0 basis-[60px] whitespace-nowrap text-[12px] text-fg-muted">{t("float.fontSize")}</span>
      <div class="qs-control flex items-center gap-1.5">
        <button
          class={iconBtnNormal}
          disabled={fontSize <= 10}
          aria-label={t("float.zoomOut")}
          onclick={onZoomOut}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="5" y1="12" x2="19" y2="12" /></svg>
        </button>
        <span class="qs-value min-w-[24px] text-center text-[12px] tabular-nums text-fg">{fontSize}</span>
        <button
          class={iconBtnNormal}
          disabled={fontSize >= 28}
          aria-label={t("float.zoomIn")}
          onclick={onZoomIn}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
        </button>
      </div>
    </div>

    <div class="qs-row flex items-center gap-2.5">
      <span class="qs-label shrink-0 basis-[60px] whitespace-nowrap text-[12px] text-fg-muted">{t("float.maxWidth")}</span>
      <div class="qs-btn-group flex flex-wrap gap-1">
        {#each MAX_WIDTH_PRESETS as preset (preset.value)}
          <button
            class={rs.settings.maxWidth === preset.value ? btnActive : btnNormal}
            onclick={() => onSetMaxWidth?.(preset.value)}>{t(preset.label)}</button
          >
        {/each}
      </div>
    </div>

    <div class="qs-row flex items-center gap-2.5">
      <span class="qs-label shrink-0 basis-[60px] whitespace-nowrap text-[12px] text-fg-muted">{t("float.lineHeight")}</span>
      <div class="qs-btn-group flex flex-wrap gap-1">
        {#each LINE_HEIGHT_PRESETS as preset (preset.value)}
          <button
            class={Math.abs(rs.settings.lineHeight - preset.value) < 0.01
              ? btnActive
              : btnNormal}
            onclick={() => onSetLineHeight?.(preset.value)}>{t(preset.label)}</button
          >
        {/each}
      </div>
    </div>

    <div class="qs-row flex items-center gap-2.5">
      <span class="qs-label shrink-0 basis-[60px] whitespace-nowrap text-[12px] text-fg-muted">{t("float.floatLayout")}</span>
      <button
        class={floatLayoutEnabled ? btnActive : btnNormal}
        onclick={onToggleFloatLayout}>{floatLayoutEnabled
          ? t("float.floatLayoutOn")
          : t("float.floatLayoutOff")}</button
      >
    </div>
  </div>

  <div
    class="qs-footer flex flex-none justify-end border-t border-float-panel-header-border px-4 pb-3 pt-2"
  >
    <button class={linkBtn} onclick={onOpenSettings}>{t("float.fullSettings")}<svg class="ml-1" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6" /></svg></button>
  </div>
</div>
